steps:
  # Run the Maven build
  - name: 'maven'
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/explorecali-be','-f', 'docker/Dockerfile', '.']

  # Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/explorecali-be:latest']
  
options:
  logging: CLOUD_LOGGING_ONLY

images: ['gcr.io/$PROJECT_ID/explorecali-be']


